# Generated by Django 5.2.13 on 2026-04-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='竞赛名称')),
                ('description', models.TextField(verbose_name='竞赛介绍')),
                ('website', models.URLField(verbose_name='官网链接')),
                ('organizer', models.CharField(max_length=100, verbose_name='主办方')),
                ('frequency', models.CharField(blank=True, max_length=50, verbose_name='举办频率')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '算法竞赛',
                'verbose_name_plural': '算法竞赛',
            },
        ),
    ]
