# Generated by Django 5.2.13 on 2026-04-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '题目标签',
                'verbose_name_plural': '题目标签',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='题目名称')),
                ('description', models.TextField(blank=True, verbose_name='题目描述')),
                ('difficulty', models.CharField(blank=True, max_length=32, verbose_name='难度')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('source_url', models.URLField(unique=True, verbose_name='源链接')),
                ('platform', models.CharField(blank=True, max_length=64, verbose_name='平台')),
                ('origin', models.CharField(blank=True, max_length=128, verbose_name='来源')),
                ('contest_name', models.CharField(blank=True, max_length=128, verbose_name='所属比赛/赛道')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.tag', verbose_name='知识点')),
            ],
            options={
                'verbose_name': '算法题目',
                'verbose_name_plural': '算法题目',
                'ordering': ['-rating', 'title'],
            },
        ),
    ]
