# Generated by Django 5.2.13 on 2026-04-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-unified_difficulty', 'title'], 'verbose_name': '算法题目', 'verbose_name_plural': '算法题目'},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='rating',
        ),
        migrations.AddField(
            model_name='problem',
            name='unified_difficulty',
            field=models.IntegerField(blank=True, null=True, verbose_name='统一难度'),
        ),
    ]
