# Generated by Django 5.2.13 on 2026-04-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_options_remove_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatijiProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiji_id', models.IntegerField(unique=True, verbose_name='码蹄集题目ID')),
                ('title', models.CharField(max_length=255, verbose_name='题目名称')),
                ('difficulty', models.CharField(blank=True, max_length=32, verbose_name='难度等级')),
                ('unified_difficulty', models.IntegerField(blank=True, null=True, verbose_name='统一难度')),
                ('description', models.TextField(blank=True, verbose_name='题目描述')),
                ('input_desc', models.TextField(blank=True, verbose_name='输入描述')),
                ('output_desc', models.TextField(blank=True, verbose_name='输出描述')),
                ('sample_input', models.TextField(blank=True, verbose_name='样例输入')),
                ('sample_output', models.TextField(blank=True, verbose_name='样例输出')),
                ('hint', models.TextField(blank=True, verbose_name='提示')),
                ('time_limit', models.CharField(blank=True, max_length=64, verbose_name='时间限制')),
                ('memory_limit', models.CharField(blank=True, max_length=64, verbose_name='内存限制')),
                ('category', models.CharField(blank=True, max_length=128, verbose_name='分类')),
                ('tags_str', models.CharField(blank=True, max_length=512, verbose_name='标签（逗号分隔）')),
                ('source_url', models.URLField(blank=True, verbose_name='原题链接')),
                ('pass_count', models.IntegerField(blank=True, null=True, verbose_name='通过人数')),
                ('submit_count', models.IntegerField(blank=True, null=True, verbose_name='提交人数')),
                ('raw_json', models.TextField(blank=True, verbose_name='原始JSON数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '码蹄集题目',
                'verbose_name_plural': '码蹄集题目',
                'ordering': ['-unified_difficulty', 'title'],
            },
        ),
    ]
