# Generated by Django 5.2.13 on 2026-04-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_matijiproblem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatijiProblem',
        ),
        migrations.AddField(
            model_name='problem',
            name='translated_description',
            field=models.TextField(blank=True, default='', verbose_name='翻译后的题目描述'),
        ),
    ]
