# Generated by Django 5.2.13 on 2026-04-16 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(verbose_name='当前水平')),
                ('target_competition', models.CharField(max_length=100, verbose_name='目标赛事')),
                ('target_award', models.CharField(max_length=100, verbose_name='目标奖项')),
                ('duration_weeks', models.IntegerField(verbose_name='训练周数')),
                ('problems_per_week', models.IntegerField(verbose_name='每周题量')),
                ('plan_data', models.JSONField(default=dict, verbose_name='训练计划数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '训练计划',
                'verbose_name_plural': '训练计划',
                'ordering': ['-created_at'],
            },
        ),
    ]
